from feapder import Item
from datetime import datetime
class SpiderProductItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i amazon_commodity.
    """
    __unique_key__ = ["product_id", "platform"]
    def __init__(self, *args, **kwargs):
        self.id = None
        self.product_id = None
        self.create_time = None
        self.sync_time = None
        self.asin = None
        self.parent_asin = None
        self.product_url = None
        self.brand = None
        self.brand_url = None
        self.big_image_url = None
        self.category_id = None
        self.category_name = None
        self.dimension_type = None
        self.dimensions = None
        self.dimensions_tag = None
        self.image_url = None
        self.market_id = None
        self.node_label_locale = None
        self.node_label_path = None
        self.node_label_path_locale = None
        self.sku = None
        self.first_review_date = None
        self.title = None
        self.station = None
        self.price = None
        self.sub_total_amount = None
        self.total_amount = None
        self.weight = None
        self.platform = None
        self.seller_id = None
        self.seller_url = None
        self.seller_name = None
        self.business_address = None
        self.business_name = None
        self.business_type = None
        self.customer_address = None
        self.email = None
        self.manager = None
        self.nation = None
        self.phone = None

    def pre_to_db(self):
        """
        入库前的处理
        """
        self.create_time = datetime.now()